/**
 * Branded, printable HTML export (Spec §10.22). Black/white/gold. Escapes all
 * dynamic content. "Print to PDF" from the browser produces the PDF artifact.
 */

interface ExportPayload {
  exportedAt: string;
  confidentiality: string;
  session: { id: string; title: string | null; date: Date; status: string; language: string };
  client: { name: string } | null;
  coach: { name: string } | null;
  summary: unknown;
  tasks: { title: string; status: string; owner: string; visibility: string }[];
  goals: { title: string; status: string; progress: number }[];
}

function esc(s: unknown): string {
  return String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function list(items: string[]): string {
  if (!items.length) return "<p class='muted'>—</p>";
  return `<ul>${items.map((i) => `<li>${esc(i)}</li>`).join("")}</ul>`;
}

export function renderSummaryHtml(p: ExportPayload): string {
  const s = (p.summary ?? {}) as Record<string, unknown>;
  const topics = Array.isArray(s.topics) ? (s.topics as string[]) : [];
  const strengths = Array.isArray(s.strengths) ? (s.strengths as string[]) : [];
  const obstacles = Array.isArray(s.obstacles) ? (s.obstacles as string[]) : [];
  const questions = Array.isArray(s.reflection_questions) ? (s.reflection_questions as string[]) : [];
  const date = new Date(p.session.date).toLocaleDateString();

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>${esc(p.session.title ?? "Session summary")}</title>
<style>
  :root{--ink:#111;--gold:#D5A640;--muted:#5F6368;--line:#e7e7e2}
  *{box-sizing:border-box}
  body{font-family:Georgia,'Times New Roman',serif;color:var(--ink);margin:0;padding:48px;max-width:820px;margin:auto;background:#fff}
  header{border-bottom:3px solid var(--gold);padding-bottom:16px;margin-bottom:24px}
  h1{font-size:26px;margin:0 0 4px}
  .brand{font-size:12px;letter-spacing:.14em;text-transform:uppercase;color:var(--gold);font-family:Arial,sans-serif}
  .meta{font-family:Arial,sans-serif;font-size:13px;color:var(--muted);margin-top:8px}
  h2{font-size:15px;letter-spacing:.06em;text-transform:uppercase;color:var(--ink);border-left:3px solid var(--gold);padding-left:10px;margin:26px 0 8px;font-family:Arial,sans-serif}
  p,li{font-size:15px;line-height:1.55}
  ul{margin:6px 0 6px 18px;padding:0}
  .muted{color:var(--muted)}
  .notice{margin-top:36px;padding:12px 14px;border:1px solid var(--line);background:#faf9f6;font-family:Arial,sans-serif;font-size:12px;color:var(--muted)}
  table{width:100%;border-collapse:collapse;font-family:Arial,sans-serif;font-size:13px;margin-top:6px}
  td,th{text-align:left;border-bottom:1px solid var(--line);padding:6px 8px}
</style></head>
<body>
  <header>
    <div class="brand">The Coach Scribe</div>
    <h1>${esc(p.session.title ?? "Session summary")}</h1>
    <div class="meta">
      Client: ${esc(p.client?.name ?? "—")} &nbsp;·&nbsp; Coach: ${esc(p.coach?.name ?? "—")}<br>
      Date: ${esc(date)} &nbsp;·&nbsp; Language: ${esc(p.session.language)} &nbsp;·&nbsp; Status: ${esc(p.session.status)}
    </div>
  </header>

  <h2>Executive summary</h2>
  <p>${esc(s.summary) || "<span class='muted'>—</span>"}</p>

  <h2>Main topics</h2>${list(topics)}
  <h2>Strengths &amp; resources</h2>${list(strengths)}
  <h2>Obstacles</h2>${list(obstacles)}

  <h2>Action items</h2>
  ${
    p.tasks.length
      ? `<table><tr><th>Task</th><th>Owner</th><th>Status</th></tr>${p.tasks
          .map((t) => `<tr><td>${esc(t.title)}</td><td>${esc(t.owner)}</td><td>${esc(t.status)}</td></tr>`)
          .join("")}</table>`
      : "<p class='muted'>—</p>"
  }

  <h2>Goals</h2>
  ${
    p.goals.length
      ? `<table><tr><th>Goal</th><th>Status</th><th>Progress</th></tr>${p.goals
          .map((g) => `<tr><td>${esc(g.title)}</td><td>${esc(g.status)}</td><td>${esc(g.progress)}%</td></tr>`)
          .join("")}</table>`
      : "<p class='muted'>—</p>"
  }

  <h2>Reflection questions</h2>${list(questions)}

  <div class="notice">
    ${esc(p.confidentiality)} Generated by The Coach Scribe on ${esc(new Date(p.exportedAt).toLocaleString())}.
    AI-assisted content reviewed and approved by the coach. Not medical, legal, or financial advice.
  </div>
</body></html>`;
}
